package aplextra

// autogenerated by go generate. do not edit.

//go:generate go run gen.go

import (
	"github.com/ktye/iv/apl"
	"github.com/ktye/iv/apl/funcs"
	"github.com/ktye/iv/apl/operators"
	"github.com/ktye/iv/aplextra/help"
	"github.com/ktye/iv/aplextra/image"
	"github.com/ktye/iv/aplextra/shell"
	"github.com/ktye/iv/aplextra/stats"
)

// RegisterAll registers all extra packages to apl.
// It also registers the standard packages apl/funcs and apl/operators.
//
// Usage:
//	import "github.com/ktye/iv/apl"
//	a := apl.New(os.Stdout)
//	RegisterAll(a)
func RegisterAll(a *apl.Apl) {
	funcs.Register(a)
	operators.Register(a)
	help.Register(a)
	image.Register(a)
	shell.Register(a)
	stats.Register(a)
}
